version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chatbi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatbi
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - chatbi-network

  redis:
    image: redis:7-alpine
    container_name: chatbi-redis
    ports:
      - "6379:6379"
    networks:
      - chatbi-network

  milvus:
    image: milvusdb/milvus:v2.3.3
    container_name: chatbi-milvus
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: [ "milvus", "run", "standalone" ]
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio
    networks:
      - chatbi-network

  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: chatbi-etcd
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: 1000
      ETCD_QUOTA_BACKEND_BYTES: 4294967296
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls=http://0.0.0.0:2379
    networks:
      - chatbi-network

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: chatbi-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    command: minio server /minio_data
    volumes:
      - minio_data:/minio_data
    networks:
      - chatbi-network

volumes:
  mysql_data:
  minio_data:

networks:
  chatbi-network:
    driver: bridge